/**
 * Gives crawlers the head tags the React app only produces after JS runs.
 *
 * The problem this solves: `vercel.json` rewrites every path to the static
 * `index.html`, so a crawler received the same head for all 553 URLs — the
 * homepage's title and, until 2026-09-29, a canonical pointing at `/`. That
 * canonical told every listing page it was a duplicate of the homepage, i.e.
 * asked search engines not to index the directory at all. Googlebot does render
 * JS, but a conflicting canonical in the initial HTML does not need rendering to
 * be obeyed, and rendering is neither prompt nor guaranteed.
 *
 * Why middleware rather than prerendering at build time: listings are published
 * from the admin UI, and the sitemap is generated live from the same view. A
 * build-time snapshot of 536 pages would be stale the moment a business is
 * published and would have to be regenerated by redeploying. This reads the
 * current row per request instead, so the head and the sitemap cannot disagree.
 *
 * This file is deliberately thin. All the logic that can be tested without an
 * edge runtime lives in `src/lib/crawlerMeta.ts` and `src/lib/headInjection.ts`;
 * what is left here is only what genuinely needs Vercel — the matcher, reading
 * the built shell, and the response.
 *
 * FAILURE POSTURE: every error path returns `undefined`, which serves the page
 * unmodified. A missing meta tag costs a crawl; a thrown middleware costs the
 * visitor the page. On failure this is allowed to do nothing, and nothing else.
 */
import { metaForPath, type RowFetcher } from "./src/lib/crawlerMeta";
import { injectHead } from "./src/lib/headInjection";

export const config = {
  // Only the routes whose head tags are route-specific. Everything else — assets,
  // the admin app, API paths — skips this entirely and costs nothing. `/` is
  // included because index.html's static head is the homepage's, but it still
  // needs the canonical that was removed from the file.
  matcher: ["/", "/directory", "/directory/:path*"],
};

/**
 * Reads rows from PostgREST with the publishable key.
 *
 * The same key the browser already ships, against a public view, so this grants
 * the edge nothing the public site does not already have. Returns null on any
 * failure so the caller falls through to serving the page unchanged.
 */
const fetchRows: RowFetcher = async (query) => {
  const url = process.env.VITE_SUPABASE_URL;
  const key = process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) return null;
  try {
    const res = await fetch(`${url}/rest/v1/${query}`, {
      headers: { apikey: key, Authorization: `Bearer ${key}`, Accept: "application/json" },
    });
    if (!res.ok) return null;
    return (await res.json()) as unknown[];
  } catch {
    return null;
  }
};

export default async function middleware(request: Request): Promise<Response | undefined> {
  try {
    const { pathname, origin } = new URL(request.url);

    const meta = await metaForPath(pathname, fetchRows);
    // Resolve the route before fetching the shell: an unmodelled route or a
    // missing row means there is nothing to inject, so the fetch would be waste.
    if (!meta) return undefined;

    // The built shell the rewrite would have served. `/index.html` is not in the
    // matcher, so this cannot recurse into this middleware.
    const shell = await fetch(`${origin}/index.html`, { headers: { Accept: "text/html" } });
    if (!shell.ok) return undefined;

    return new Response(injectHead(await shell.text(), meta), {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        // Short shared cache: a listing's name changing should surface within a
        // couple of minutes, but a repeat crawl should not mean a read per page.
        "Cache-Control": "public, max-age=0, s-maxage=120, stale-while-revalidate=600",
      },
    });
  } catch {
    return undefined;
  }
}
