/**
 * sitemap
 *
 * Generates sitemap.xml from live data. Served at /sitemap.xml via a Vercel
 * rewrite (see vercel.json) — the static public/sitemap.xml it replaced went
 * stale the moment the site pivoted from Santa Clarita plumbing to the Valley
 * Home Pros directory, and was advertising six URLs that render the 404 page.
 *
 * Two rules this file exists to enforce:
 *
 *  1. Every URL here must correspond to a real route in src/App.tsx. A sitemap
 *     full of 404s is worse than no sitemap.
 *  2. Listings come from `public_business_listings`, never from `businesses`.
 *     That view exposes published rows only, so an unpublished listing can
 *     never leak into the sitemap and get crawled before it is ready.
 */
import { serviceRoleKey as readServiceRoleKey } from "../_shared/supabaseKeys.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

/**
 * The canonical public host. `SITE_DOMAIN` overrides it, but the fallback is
 * the real domain rather than a preview host: the previous default was the
 * Lovable preview URL, which would have pointed every entry at the wrong site.
 */
const DEFAULT_DOMAIN = "homequotelink.com";

interface Entry {
  loc: string;
  lastmod?: string;
  changefreq: string;
  priority: string;
}

/**
 * Routes that exist in App.tsx and are worth indexing. Deliberately excludes
 * /thank-you, /feedback, /login, /account, /provider/*, /reset-password and
 * /admin/* — those are transactional, token-gated, or private.
 */
function staticEntries(today: string): Entry[] {
  return [
    { loc: "/", changefreq: "weekly", priority: "1.0", lastmod: today },
    { loc: "/directory", changefreq: "daily", priority: "0.9", lastmod: today },
    { loc: "/blog", changefreq: "daily", priority: "0.8", lastmod: today },
    { loc: "/providers", changefreq: "weekly", priority: "0.7", lastmod: today },
    { loc: "/faq", changefreq: "monthly", priority: "0.7", lastmod: today },
    { loc: "/services/emergency-tree-removal", changefreq: "monthly", priority: "0.8", lastmod: today },
    { loc: "/services/brush-clearing", changefreq: "monthly", priority: "0.8", lastmod: today },
    { loc: "/services/palm-tree-trimming", changefreq: "monthly", priority: "0.8", lastmod: today },
    { loc: "/privacy", changefreq: "yearly", priority: "0.3" },
    { loc: "/terms", changefreq: "yearly", priority: "0.3" },
  ];
}

/** XML-escapes a URL path. Slugs are generated by slugify() so this is belt-and-braces. */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderEntry(siteUrl: string, e: Entry): string {
  return `
  <url>
    <loc>${xmlEscape(siteUrl + e.loc)}</loc>${e.lastmod ? `
    <lastmod>${e.lastmod}</lastmod>` : ""}
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority}</priority>
  </url>`;
}

/**
 * Retries a Supabase query on failure. Exists because Supabase's log data
 * (checked 2026-08-17, in the window right after legacy keys were disabled
 * project-wide) shows this function's three queries intermittently fail with
 * PGRST303 ("JWT claims decoding failed") — roughly 1 in 4 requests, with a
 * concurrent sibling query using the identical client and key succeeding in
 * the same request. That rules out anything in this file: one `createClient`
 * call, one synchronous key, no per-request auth computation to race. The
 * failure is upstream, in Supabase's own gateway — not fixable here, only
 * survivable by retrying.
 *
 * `queryFn` must be a factory, not a Promise: Supabase's query builders are
 * single-use, so awaiting the same one twice does not re-issue the request.
 */
async function withRetry<R extends { error: { message: string } | null }>(
  queryFn: () => PromiseLike<R>,
  label: string,
  retries = 2,
  delayMs = 300,
): Promise<R> {
  let result: R;
  for (let attempt = 0; attempt <= retries; attempt++) {
    result = await queryFn();
    if (!result.error) return result;
    console.warn(`[sitemap] ${label} query failed (attempt ${attempt + 1}/${retries + 1}): ${result.error.message}`);
    if (attempt < retries) await new Promise((resolve) => setTimeout(resolve, delayMs));
  }
  // All attempts exhausted — return the last (failed) result. The caller's
  // existing `?? []` fallback keeps this from crashing sitemap generation;
  // it just means this one section is missing until the next successful run.
  return result!;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      readServiceRoleKey(),
    );

    const domain = Deno.env.get("SITE_DOMAIN") || DEFAULT_DOMAIN;
    const siteUrl = `https://${domain}`;
    const today = new Date().toISOString().split("T")[0];

    // All three retried: the intermittent upstream auth failure withRetry
    // guards against was observed on all three tables, not just one.
    const [listingsRes, postsRes, buyersRes] = await Promise.all([
      // Published listings only — this view filters is_published AND
      // archived_at for us, so archived businesses never reach the sitemap.
      withRetry(
        () => supabase.from("public_business_listings").select("slug, city_slug, created_at"),
        "public_business_listings",
      ),
      // posts and buyers are read directly rather than through a view, so the
      // archived filter has to be explicit here — an archived row must not be
      // advertised to search engines.
      withRetry(
        () =>
          supabase
            .from("posts")
            .select("slug, updated_at, published_at, tags, category")
            .eq("status", "published")
            .is("archived_at", null),
        "posts",
      ),
      withRetry(
        () => supabase.from("buyers").select("id").eq("is_active", true).is("archived_at", null),
        "buyers",
      ),
    ]);

    const entries: Entry[] = [...staticEntries(today)];

    // ── Directory: one page per city that actually has a listing, plus each listing.
    const listings = listingsRes.data ?? [];
    const cities = new Set<string>();
    for (const l of listings as { slug: string; city_slug: string; created_at: string | null }[]) {
      if (!l.city_slug || !l.slug) continue;
      cities.add(l.city_slug);
      entries.push({
        loc: `/directory/${l.city_slug}/${l.slug}`,
        lastmod: (l.created_at ?? "").split("T")[0] || today,
        changefreq: "weekly",
        priority: "0.7",
      });
    }
    for (const city of cities) {
      entries.push({ loc: `/directory/${city}`, lastmod: today, changefreq: "daily", priority: "0.8" });
    }

    // ── Blog posts, plus the tag and category archives they generate.
    const posts = (postsRes.data ?? []) as {
      slug: string; updated_at: string | null; published_at: string | null;
      tags: string[] | null; category: string | null;
    }[];

    const tags = new Set<string>();
    const categories = new Set<string>();
    for (const p of posts) {
      entries.push({
        loc: `/blog/${p.slug}`,
        lastmod: (p.updated_at || p.published_at || "").split("T")[0] || today,
        changefreq: "monthly",
        priority: "0.6",
      });
      if (Array.isArray(p.tags)) for (const t of p.tags) if (t) tags.add(t);
      if (p.category) categories.add(p.category);
    }
    for (const t of tags) {
      entries.push({ loc: `/blog/tag/${encodeURIComponent(t)}`, lastmod: today, changefreq: "weekly", priority: "0.4" });
    }
    for (const c of categories) {
      entries.push({ loc: `/blog/category/${encodeURIComponent(c)}`, lastmod: today, changefreq: "weekly", priority: "0.4" });
    }

    // ── Provider detail pages.
    for (const b of (buyersRes.data ?? []) as { id: string }[]) {
      entries.push({ loc: `/providers/${b.id}`, changefreq: "weekly", priority: "0.5" });
    }

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${entries.map((e) => renderEntry(siteUrl, e)).join("")}
</urlset>`;

    // NOTE: the Content-Type set here survives on POST but NOT on GET — the
    // Supabase edge gateway rewrites GET responses to text/plain, and no
    // function-side change fixes it (verified: POST returns text/xml from this
    // exact code, GET returns text/plain). vercel.json therefore re-asserts the
    // header on the /sitemap.xml route, which is the path crawlers actually use.
    const headers = new Headers(corsHeaders);
    headers.set("Content-Type", "text/xml; charset=utf-8");
    // Crawlers re-fetch often; an hour keeps new listings discoverable without
    // regenerating on every hit.
    headers.set("Cache-Control", "public, max-age=3600");

    return new Response(xml, { headers });
  } catch (err) {
    console.error("[sitemap]", err);
    return new Response("Internal Server Error", { status: 500, headers: corsHeaders });
  }
});
